version: '3'
services:
  dst-dedicated:
    build: .
    network_mode: "host"
    volumes:
      - ./DoNotStarveTogether:/home/steam/.klei/DoNotStarveTogether
      - steamapp:/home/steam/dontstarvetogether_dedicated_server

volumes:
  steamapp:
